version: '3.8'

services:
  ufbank-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ufbank-api
    ports:
      - '3000:3000'
      - '3002:3002'
    environment:
      NODE_ENV: development
      PORT: 3000

      PAGAMENTOS_HOST: pagamentos-service
      PAGAMENTOS_PORT: 3001
      UFBANK_EVENT_HOST: 0.0.0.0
      UFBANK_EVENT_PORT: 3002
    volumes:
      - .:/usr/src/app
      - ./dist:/usr/src/app/dist
    depends_on:
      - pagamentos-service
    networks:
      - default
      - ufbank-network
    command: npm run start:dev
  
  pagamentos-service:
    build:
      context: .
      dockerfile: Dockerfile.pagamentos
    container_name: ufbank-pagamentos-service
    ports:
      - '3001:3001'
    environment:
      NODE_ENV: development
      PAGAMENTOS_HOST: 0.0.0.0
      PAGAMENTOS_PORT: 3001
      
      UFBANK_HOST: ufbank-api
      UFBANK_EVENT_PORT: 3002
    # Executando em modo production: n√£o monte volumes que sobrescrevam build
    # Para desenvolvimento, comente as linhas abaixo e use `command: npm run start:pagamentos`.
    networks:
      - default
      - ufbank-network
    restart: unless-stopped

networks:
  default:
    driver: bridge
  ufbank-network:
    driver: bridge